### PR TITLE
Bug 2089313: Multipath fix for passive paths

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Review by iurygregory — APPROVED** [review]

**Comment by iurygregory** [comment]
humm I just noticed we are not running pre-validation jobs O.o

**Comment by iurygregory** [comment]
Yay habemus prevalidation jobs

**Comment by iurygregory** [comment]
@elfosardo I think we are good to test - based on prevalidation jobs) I\m removing the `hold`

/unhold

**Comment by elfosardo** [comment]
packages were tagged in production, we'll retest after they show up in the repo

**Pull request merged**
