### PR TITLE
Bug 1948513: Add support for no_proxy

### PR DESCRIPTION
**Pull request by e-minguez**
Related to https://github.com/openshift/ironic-rhcos-downloader/pull/39

### CODE REVIEW

**Comment by stbenjam** [comment]
@e-minguez Would you mind opening the same PR upstream too? https://github.com/metal3-io/ironic-ipa-downloader/blob/master/get-resource.sh

**Comment by e-minguez** [comment]
> @e-minguez Would you mind opening the same PR upstream too? https://github.com/metal3-io/ironic-ipa-downloader/blob/master/get-resource.sh

https://github.com/metal3-io/ironic-ipa-downloader/pull/18 👍🏻

**Comment by e-minguez** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1948513

**Comment by stbenjam** [comment]
/retitle Bug 1948513: Add support for no_proxy

**Comment by stbenjam** [comment]
Put it in the title like that ^

**Pull request merged**
