### PR TITLE
Update version of ipa ramdisk

### PR DESCRIPTION
**Pull request by elfosardo**
Use version 2021.test.1-20210302.1.el8
That includes openstack-ironic-python-agent-6.6.1-0.20210302161246.77bc398.el8

Also account for ipa ramdisk tarball name change

### CODE REVIEW

**Comment by hardys** [comment]
Image build is failing:

```
 No match for argument: ironic-images-ipa-x86_64 >= 2021.test.1-20210302.1.el8
Error: Unable to find a match: ironic-images-ipa-x86_64 >= 2021.test.1-20210302.1.el8 
```

**Comment by elfosardo** [comment]
this depends on https://github.com/openshift/release/pull/16583

**Comment by derekhiggins** [comment]
> this depends on [openshift/release#16583](https://github.com/openshift/release/pull/16583)

I see, afraid I don't seem to be able to /lgtm it

**Comment by elfosardo** [comment]
superseded by https://github.com/openshift/ironic-ipa-downloader/pull/62

**Pull request closed without merging**
