### PR TITLE
Bug 2070519: Multipath fix for passive paths

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Comment by elfosardo** [comment]
seems like repo cache has not been updated yet, let's wait a bit before retesting again

**Comment by iurygregory** [comment]
maybe later we should drop the e2e-metal-ipi like we did in other repos

**Review by iurygregory — APPROVED** [review]

**Comment by iurygregory** [comment]
Now we just need to wait for the packages in 4.9 and tag :D

**Review by iurygregory — APPROVED** [review]

**Pull request merged**
