### PR TITLE
Bug 1905004: Use new ironic-python-agent images

### PR DESCRIPTION
**Pull request by elfosardo**
Simplify ironic-ipa-downloader to use the new ironic-python-agent
images built with latest ironic-python-agent code.

Bugfixes include:
- new version of eventlet to prevent https://github.com/eventlet/eventlet/issues/308
- new version of python-hardware with fixes for https://bugs.launchpad.net/tripleo/+bug/1900158 and https://bugs.launchpad.net/tripleo/+bug/1901917
- new version of ipa-builder to allow easier downstream customization and testing

(cherry picked from commit 560d74b8a9b2f1bcd59314c5c09567914c2f4730)

### CODE REVIEW

**Comment by dtantsur** [comment]
You need to make the bug validator and the CI happy.

**Comment by elfosardo** [comment]
I may have forgotten again to tag the correct package first

**Comment by derekhiggins** [comment]
The descriptions says this is being done to Simplify things, do we have to switch 4.6 to the new ironic-images-ipa package?
If we don't have to do this does it come with much risk v.s. keeping the old method?

**Comment by elfosardo** [comment]
> The descriptions says this is being done to Simplify things, do we have to switch 4.6 to the new ironic-images-ipa package?
> If we don't have to do this does it come with much risk v.s. keeping the old method?

we are switching 4.6 to ironic-images pkg as we did for 4.7
the ironic-images pkg can be rebuilt every time a new patch for ironic-python-agent comes out and it is tested downstream, before being tagged
it includes all the changes and dependencies required to run ipa
there are actually fewer risks as we switch the hacks that were in place here to a proper build and testing pipeline

**Comment by elfosardo** [comment]
| /test e2e-metal-ipi
-- | --

**Comment by elfosardo** [comment]
heh I will have to check this locally :/

**Comment by stbenjam** [comment]
This probably needs to be a second BZ, as https://github.com/openshift/ironic-ipa-downloader/pull/53 used up 1899190 and is going to ship in the next z-Stream

**Review by dtantsur — APPROVED** [review]
/lgtm

**Pull request merged**
