### PR TITLE
Bug 1935419: Fix failed to scale worker using virtualmedia on Dell R640

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Comment by derekhiggins** [comment]
/test prevalidation-e2e-metal-ipi-prevalidation

@elfosardo this is the job we're hoping to see pass while the others fail is that correct?

**Comment by elfosardo** [comment]
/hold
installing wrong ironic images base package

**Comment by elfosardo** [comment]
> /test prevalidation-e2e-metal-ipi-prevalidation
> 
> @elfosardo this is the job we're hoping to see pass while the others fail is that correct?

correct, plus ci/prow/prevalidation-images which is just the image build

**Comment by elfosardo** [comment]
failure is verified caused by the ipa ramdisk installed, it's missing a package
we're going to compile and tag a new one

**Pull request merged**
