### PR TITLE
Bug 1908493: Update version of ironic-images package

### PR DESCRIPTION
**Pull request by elfosardo**
Also introduce variable for the ironic-images package version

### CODE REVIEW

**Comment by elfosardo** [comment]
we need https://github.com/openshift/release/pull/14529 to make this work correctly

**Comment by elfosardo** [comment]
the test image we're using for prevalidation can't be tagged in production, so at the moment this can't pass
the proces of rebuilding the image for production requires signing some packages, this is currently ongoing and we should have the new image before end of the week

**Review by dtantsur — APPROVED** [review]

**Pull request merged**
