### PR TITLE
Bug 1873976: Install packages from file content

### PR DESCRIPTION
**Pull request by elfosardo**
An improvement for testing and customization, moving all the
files we need to install in the ipa-ramdisk to a file and having
dnf read its content.
This allows exotic compositions of sources, like urls and local dirs,
without having to touch the Dockerfile.

### CODE REVIEW

**Comment by derekhiggins** [comment]
lgtm, just trying to understand the this will end up looking like, where are you hoping to plug in the other sources?
The commit message mentions not having to touch Dockerfile, did you mean to say chrooted.sh ?

**Comment by elfosardo** [comment]
> lgtm, just trying to understand the this will end up looking like, where are you hoping to plug in the other sources?
> The commit message mentions not having to touch Dockerfile, did you mean to say chrooted.sh ?
@derekhiggins I did mean chrooted, I admit I did a lazy copy-paste from the other PRs :)

**Review by dtantsur — APPROVED** [review]
/lgtm

**Pull request merged**
