### PR TITLE
Bug 1963210: Add support for no_proxy

### PR DESCRIPTION
**Pull request by kirankt**
This is a manual backport of Bug 1948513

### CODE REVIEW

**Comment by sdodson** [comment]
@kirankt (patch-manager) Can you please pursue peer review on this? The other PR for this bug is ready to go but we should merge both at the same time.

**Comment by kirankt** [comment]
> @kirankt (patch-manager) Can you please pursue peer review on this? The other PR for this bug is ready to go but we should merge both at the same time.

Yes, sir. Working on it. Should get approval soon. Thanks for the heads up.

**Comment by kirankt** [comment]
@sdodson . This BZ is ready for your cherry-pick approval. Thanks.

**Pull request merged**
