### PR TITLE
Bug 1894992: Add tenacity to installed packages, and hack eventlet to workaround a bug

### PR DESCRIPTION
**Pull request by stbenjam**
Adds on to https://github.com/openshift/ironic-ipa-downloader/pull/46 to apply a hack for eventlet.

### CODE REVIEW

**Comment by stbenjam** [comment]
Thanks I got what I needed from this :) I was just using this to get a release image built.

/close

**Comment by stbenjam** [comment]
Actually this PR might be the one to supersede https://github.com/openshift/ironic-ipa-downloader/pull/46 as additional fixes are needed.

**Comment by stbenjam** [comment]
/hold

Pending passing CI

**Review by dtantsur — APPROVED** [review]
/lgtm

**Comment by stbenjam** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1895109 tracks fixing eventlet

**Pull request merged**
