### PR TITLE
Bug 1963204: Update IPA ramdisk for RHEL 8.4

### PR DESCRIPTION
**Pull request by lhh**
Resolves: rhbz#1963204

Signed-off-by: Lon Hohberger <lhh@redhat.com>

### CODE REVIEW

**Comment by lhh** [comment]
Waiting to retest for a few hours - I just built the packages, so the test repos are behind.

**Review by dtantsur — APPROVED** [review]

**Comment by elfosardo** [comment]
please unhold and retest ONLY AFTER https://github.com/openshift/release/pull/18892 merges, thanks

**Comment by elfosardo** [comment]
&nbsp; | /test images
-- | --

**Pull request merged**
